#!/bin/bash -l

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export FASTLANE_DONT_STORE_PASSWORD="1"
export SPACESHIP_SKIP_2FA_UPGRADE="1"
export FASTLANE_USER="yen-chia.lin@adidas.com"
# export FASTLANE_PASSWORD="Testtest1234"

# HOW-TO generate new fastlane session cookie: https://docs.fastlane.tools/best-practices/continuous-integration/#spaceauth
#
# In case session has expired, use the following command to generate a new one and paste it here:
#
#           fastlane spaceauth -u user@example.org --copy_to_clipboard
#
# Now paste in the session cookie into the following variable:
# Cookie generated by YEL on 2021-06-29:
SESSION_COOKIE="---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: DAWTKNV272def7249c09ad793ad4fe0ad2c27499389d7b7a36204a7f0815f74a65df36554b57603e52433921802049769d789aa0d8a15ea812918a691022fe826e0c41ad29108daae64c8b7130fd63e11be2512d28c213e0573341a13dbd71d7742c793d594ef1a204946e0b0b8fd2de2c51d0dca98bf5f60dd216453ef46e908f0707ef915841eb8da1aaa84d79e08bd293103f546033966f73a4d8257e7dcd19bc923d6439237e18fa05686b00fd20a4817f797264de6fb1b9e52ea6cb64278be7ba7e1cb7616a1839ef6f8ebdc27000f2c650a2f66c5612c2ca59c589b29eb62bbc4f554b125244f7d741f95808a76c1795414cadc9a8332633bed12ff062c9c9928c8f6c79e27ddfb2e94b9a3e19c67d2f46e49d67b76fe775e63e7de22ac658e7ba7c9aeba4e4833c73f86f93ac5476b4c6bc75a2c685c7a87c8fd049c38f91a961a661aaf6fa7351d7235e5f6de87d4e26a237a3c47633bde5bc1b139a709f2e7150cdf02ce6188a9d3c16f0a2a90561331abafe55a68bd9610de7dfe6f5d51121f3166eeac7c3bf6deaec6a38e46a8715a067b95f78c4d1d968a1db2ea6d0e1b467bdb6ca18ac0262c87163c2e24343d224f1e4e02900389ee58c8d2045f82b11ac120416f4061d990198e75747716336b4bbdc9666b371650150e7775581cf4562e17e8b995a4133fd6cbe0589acc8737116c76c1455997ab935cbff04c3773a3220d8cb30bf9a650e1af73ac2605773975be43b6756c8bd21590d1c2084d08262356234373265613962613638323064303964336534636234363134306162333963316439656232MVRYV2\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires:\n  max_age:\n  created_at: 2021-06-29 16:45:18.239002000 +02:00\n  accessed_at: 2021-06-29 16:45:18.249945000 +02:00\n- !ruby/object:HTTP::Cookie\n  name: DES54ed75ab41a54e67483e9622e43ec3c53\n  value: HSARMTKNSRVXWFlavo1RDIhV9HwsVproj2XeS16XeXRKu5wRxe4Wq9T8PAjivM0ZKRc+49zdiC4MpwxAhj96zpIkrlx/BQfBqB6EGyr4whsiUgpvJ+nwort0jIc9weeX+yZnKkGCwWeiHqPMGNmLpAdvdzOeuzFw43+Vxoi/feTjeq4VmJkBekKiH6hr+g==SRVX\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires:\n  max_age: 2592000\n  created_at: &1 2021-06-29 16:45:18.238898000 +02:00\n  accessed_at: *1\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQ5Nzc5MTgsImp0aSI6IkxILUtNUk9Ia3pBbjhhQklQbm9FMFEifQ.NIBUW4VCnxY1YZ8PO75PmoI1Ncwja1CI8GE2aJXG_rI\n  domain: appstoreconnect.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires:\n  max_age: 1800\n  created_at: &2 2021-06-29 16:45:18.899984000 +02:00\n  accessed_at: *2\n"

FASTLANE_SESSION=$SESSION_COOKIE xcversion install "13 beta 2" --shared-cache='/Volumes/development/Mobile/iPhone/Software/XcodeInstallCache'
